### PR TITLE
Add nugettrends.com as NuGet provider

### LINKED ISSUE #6: Get NuGet (.NET) data
.NET ecosystem package manager is nuget.org. Unfortunately they don't offer historic data but a friend and I started a project to offer this service: https://github.com/NuGetTrends/nuget-trends

Would it be interesting to you to add NuGet support through nugettrends.com API?

### PR DESCRIPTION
**Pull request by stayallive**
Fixes #6

### CODE REVIEW

**Comment by bruno-garcia** [comment]
Cool stuff! 
One thing though: Do you think it would be possible to link to NuGetTrends as the data source instead? 
Just wondering if there's a way to give the site some sort of credit :)

**Comment by stayallive** [comment]
If you look at the `$sources` in the class you can see I link to NuGetTrends as the source, that link wil be displayed in the footer with the rest of the data sources. It still does say `NuGet` instead of `NuGetTrends` not sure how I want to do it if the source is "unofficial", so that might change still before we're pushing this live 👍 

https://github.com/irongate/pkgtrends/pull/7/files#diff-6fee2a9fee79be93a1e7e1b4dd50be69R29

**Comment by bruno-garcia** [comment]
> If you look at the $sources in the class you can see I link to NuGetTrends as the source, that link wil be displayed in the footer with the rest of the data sources. 

Right, I missed that, sorry.

> It still does say NuGet instead of NuGetTrends not sure how I want to do it if the source is "unofficial", so that might change still before we're pushing this live 👍

OK, no biggie. Thanks!

**Comment by stayallive** [comment]
I am going to close this since there hasn't been any movement, #6 remains open to track the feature request in case we want to restart this again!

**Pull request closed without merging**
